### ISSUE TITLE
How to setup template once to have a single command ?

### ISSUE THREAD

**Issue by flip111** [tpapp/PkgSkeleton.jl#16]
I would like to create a template to my specifications and then be able to run on the command line (not inside of julia) some command to start a new package with my template. Is there any way to do this?

Additionally is there a way to skip the initialization of a git repository?

**Comment by tpapp** [comment]
Yes, with something like `julia -e `import PkgSkeleton; PkgSkeleton.generate(...)`.

I will add an option to skip git initialization.

**Comment by tpapp** [comment]
I just realized that we already have a `git_init` option.
