### ISSUE TITLE
Arbitrary user_replacements?

### ISSUE THREAD

**Issue by chris-b1** [tpapp/PkgSkeleton.jl#44]
Hi @tpapp  - thanks for the package!  I was wondering if it'd be a reasonable addition to allow arbitrary keys/values to be passed to the `user_replacements` kwarg in `generate`?

In my particular usecase I want to do something like this, where `{CONTENTS}` is some dynamically loaded content from another file.

{PKGNAME.jl}
```
module {PKGNAME}

{CONTENTS}

end 
```

**Comment by tpapp** [comment]
Great idea, I will make a PR next week.
